artifacts_root: artifacts

data_ingestion:
  root_di: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/Singhsansar/Machine-Learning-Project/main/Dataset/finalTrain.csv
  local_data_file: artifacts/data_ingestion/finalTrain.csv
